import Testing
@testable import StitchPilotCore

/// `EmbroideryObject.isApplique` (a placement outline, then a tack-down
/// outline slightly inset, sewn before the object's own normal stitching)
/// is generated by `DigitizePipeline`'s private `appliqueRuns`/
/// `rawStitchRuns` -- exercised here through the public `flatten` entry
/// point, the same way every other stitch-type behavior in this engine is
/// tested.
struct AppliqueTests {
    func square() -> VectorShape {
        VectorShape(subPaths: [SubPath(points: [
            Point2D(0, 0), Point2D(20, 0), Point2D(20, 20), Point2D(0, 20),
        ], closed: true)])
    }

    @Test func appliqueObjectProducesMoreStitchesThanTheSameNonAppliqueObject() throws {
        var params = StitchGenerationParameters()
        params.satinDensityMM = 0.4
        let plainObject = EmbroideryObject(name: "Plain", shape: square(), stitchType: .tatamiFill,
                                            threadColor: .generic(RGBColor(hex: 0x000000)), parameters: params)
        var appliqueObject = plainObject
        appliqueObject.isApplique = true

        let plainPlan = try DigitizePipeline.flatten(StitchDocument(name: "Plain", physicalWidthMM: 20, physicalHeightMM: 20, objects: [plainObject]))
        let appliquePlan = try DigitizePipeline.flatten(StitchDocument(name: "Applique", physicalWidthMM: 20, physicalHeightMM: 20, objects: [appliqueObject]))

        #expect(appliquePlan.stitchCount > plainPlan.stitchCount, "the placement + tack-down outlines should add real stitches on top of the object's own normal fill")
    }

    /// The placement and tack-down outlines, plus the main fill, must sew
    /// as three genuinely separate runs (trim + jump between each) --
    /// confirms `rawStitchRuns` returns them as distinct runs rather than
    /// one continuous bridged path, matching how a real applique workflow
    /// needs to pause between them for the fabric to actually be placed.
    @Test func appliqueRunsAreSeparatedByTrims() throws {
        var params = StitchGenerationParameters()
        params.satinDensityMM = 0.4
        var object = EmbroideryObject(name: "Applique", shape: square(), stitchType: .tatamiFill,
                                       threadColor: .generic(RGBColor(hex: 0x000000)), parameters: params)
        object.isApplique = true
        let doc = StitchDocument(name: "Applique", physicalWidthMM: 20, physicalHeightMM: 20, objects: [object])
        let plan = try DigitizePipeline.flatten(doc)

        // Every trim inside this single-object, single-color plan is one
        // of the internal run boundaries this test cares about (the only
        // other trim is the plan's own final one before `.end`).
        let internalTrims = plan.commands.dropLast(2).filter { if case .trim = $0 { return true } else { return false } }
        #expect(internalTrims.count >= 2, "expected a trim between placement->tack-down and another between tack-down->main stitching")
    }

    /// The tack-down outline insets from the placement outline -- confirms
    /// it's actually a smaller loop, not an identical duplicate trace.
    @Test func tackDownOutlineIsInsetFromThePlacementOutline() throws {
        var params = StitchGenerationParameters()
        params.satinDensityMM = 0.4
        var object = EmbroideryObject(name: "Applique", shape: square(), stitchType: .runningStitch,
                                       threadColor: .generic(RGBColor(hex: 0x000000)), parameters: params)
        object.isApplique = true
        let doc = StitchDocument(name: "Applique", physicalWidthMM: 20, physicalHeightMM: 20, objects: [object])
        let plan = try DigitizePipeline.flatten(doc)

        // With a plain running-stitch main pass, all three runs (placement,
        // tack-down, main outline) trace the same 20x20 square boundary at
        // slightly different insets -- their combined bounding box should
        // still sit close to the full 20x20 extent (placement, at the true
        // boundary, is included), but there should be real interior
        // structure (not every stitch on the exact same 0/20 boundary)
        // from the inset tack-down pass.
        let points = plan.commands.compactMap { $0.point }
        let interiorPoints = points.filter { $0.x > 0.5 && $0.x < 19.5 && $0.y > 0.5 && $0.y < 19.5 }
        #expect(!interiorPoints.isEmpty, "expected some stitches strictly inside the placement boundary from the inset tack-down pass")
    }

    @Test func nonAppliqueObjectIsUnaffected() throws {
        var params = StitchGenerationParameters()
        params.satinDensityMM = 0.4
        let object = EmbroideryObject(name: "Plain", shape: square(), stitchType: .tatamiFill,
                                       threadColor: .generic(RGBColor(hex: 0x000000)), parameters: params)
        #expect(object.isApplique == false, "applique must default to off for every existing/new object")
    }
}
